package proto.controllers;

import proto.models.Category;
import proto.repositories.CategoryRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;


/**
 * Rest controller that uses repository to retrive all product categories
 */

 @RestController
 @RequestMapping("/categories")
 public class CategoryController {
    @Autowired // This means to get the bean called categoryRepository
    // Which is auto-generated by Spring, we will use it to handle the data
     private CategoryRepository categoryRepository;
/*
     public CategoryController(CategoryRepository categoryRepository){
         this.categoryRepository = categoryRepository;
     }
     */

     @GetMapping("/all")
     public @ResponseBody Iterable<Category> all() {
         return this.categoryRepository.findAll();
     }

     @PostMapping("/add")
     public @ResponseBody String addNewCategory(@RequestParam String name, @RequestParam String description,
                                                @RequestParam String imageUrl) {

            // @ResponseBody means the returned String is the response, not a view name
            // @RequestParam means it is a parameter from the GET or POST request
            Category cat = new Category(name, description, imageUrl);
            this.categoryRepository.save(cat);
            return "saved";
    }

 }